name: fl_mlkit_identify_language
description: Identify the language of text with ML Kit on Android And IOS
version: 0.0.1
repository: https://github.com/Wayaer/fl_mlkit_identify_language.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:

  plugin:
    platforms:
      android:
        package: fl.mlkit.identify.language
        pluginClass: FlMlkitIdentifyLanguagePlugin
      ios:
        pluginClass: FlMlkitIdentifyLanguagePlugin